# Generated by Django 4.1.5 on 2023-01-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timingtodo',
            name='timing',
            field=models.DateField(default='2022-01-20'),
        ),
    ]
